name: Build Android APK

on:
  push:
    branches: [ main ]  # یا 'master' اگر ریپوت اون باشه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KaiOSLauncher-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
